language: scala

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2

jdk:
 - oraclejdk8

scala:
 - 2.11.8

after_success:
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - sbt docker:publish